# Generated by Django 5.2.11 on 2026-02-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='branch',
            new_name='name',
        ),
    ]
