/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppRole = IDL.Variant({
  'admin' : IDL.Null,
  'student' : IDL.Null,
  'recruiter' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'selected' : IDL.Null,
  'shortlisted' : IDL.Null,
});
export const JobApplication = IDL.Record({
  'status' : ApplicationStatus,
  'appliedAt' : IDL.Int,
  'jobId' : IDL.Nat,
  'student' : IDL.Principal,
});
export const JobPosting = IDL.Record({
  'title' : IDL.Text,
  'postedBy' : IDL.Principal,
  'jobType' : IDL.Variant({ 'job' : IDL.Null, 'internship' : IDL.Null }),
  'description' : IDL.Text,
  'deadline' : IDL.Int,
  'company' : IDL.Text,
  'requirements' : IDL.Vec(IDL.Text),
  'stipendOrSalary' : IDL.Text,
  'location' : IDL.Text,
});
export const StudentProfile = IDL.Record({
  'gpa' : IDL.Float64,
  'name' : IDL.Text,
  'graduationYear' : IDL.Nat,
  'email' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'resumeUrl' : IDL.Text,
});
export const Stats = IDL.Record({
  'placements' : IDL.Nat,
  'totalStudents' : IDL.Nat,
  'totalJobs' : IDL.Nat,
  'totalApplications' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyToJob' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'assignAppRole' : IDL.Func([IDL.Principal, AppRole], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'getAllApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getAllJobs' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'getApplicationsForJob' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAppRole' : IDL.Func([], [IDL.Opt(AppRole)], ['query']),
  'getMyApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postJob' : IDL.Func([JobPosting], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([StudentProfile], [], []),
  'seedData' : IDL.Func([], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  'updateJob' : IDL.Func([IDL.Nat, JobPosting], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppRole = IDL.Variant({
    'admin' : IDL.Null,
    'student' : IDL.Null,
    'recruiter' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'selected' : IDL.Null,
    'shortlisted' : IDL.Null,
  });
  const JobApplication = IDL.Record({
    'status' : ApplicationStatus,
    'appliedAt' : IDL.Int,
    'jobId' : IDL.Nat,
    'student' : IDL.Principal,
  });
  const JobPosting = IDL.Record({
    'title' : IDL.Text,
    'postedBy' : IDL.Principal,
    'jobType' : IDL.Variant({ 'job' : IDL.Null, 'internship' : IDL.Null }),
    'description' : IDL.Text,
    'deadline' : IDL.Int,
    'company' : IDL.Text,
    'requirements' : IDL.Vec(IDL.Text),
    'stipendOrSalary' : IDL.Text,
    'location' : IDL.Text,
  });
  const StudentProfile = IDL.Record({
    'gpa' : IDL.Float64,
    'name' : IDL.Text,
    'graduationYear' : IDL.Nat,
    'email' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'resumeUrl' : IDL.Text,
  });
  const Stats = IDL.Record({
    'placements' : IDL.Nat,
    'totalStudents' : IDL.Nat,
    'totalJobs' : IDL.Nat,
    'totalApplications' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyToJob' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'assignAppRole' : IDL.Func([IDL.Principal, AppRole], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'getAllApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'getAllJobs' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
    'getApplicationsForJob' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAppRole' : IDL.Func([], [IDL.Opt(AppRole)], ['query']),
    'getMyApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postJob' : IDL.Func([JobPosting], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([StudentProfile], [], []),
    'seedData' : IDL.Func([], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
    'updateJob' : IDL.Func([IDL.Nat, JobPosting], [], []),
  });
};

export const init = ({ IDL }) => { return []; };