/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'admin' : null } |
  { 'student' : null } |
  { 'recruiter' : null };
export type ApplicationStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'selected' : null } |
  { 'shortlisted' : null };
export interface JobApplication {
  'status' : ApplicationStatus,
  'appliedAt' : bigint,
  'jobId' : bigint,
  'student' : Principal,
}
export interface JobPosting {
  'title' : string,
  'postedBy' : Principal,
  'jobType' : { 'job' : null } |
    { 'internship' : null },
  'description' : string,
  'deadline' : bigint,
  'company' : string,
  'requirements' : Array<string>,
  'stipendOrSalary' : string,
  'location' : string,
}
export interface Stats {
  'placements' : bigint,
  'totalStudents' : bigint,
  'totalJobs' : bigint,
  'totalApplications' : bigint,
}
export interface StudentProfile {
  'gpa' : number,
  'name' : string,
  'graduationYear' : bigint,
  'email' : string,
  'skills' : Array<string>,
  'resumeUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyToJob' : ActorMethod<[bigint], bigint>,
  'assignAppRole' : ActorMethod<[Principal, AppRole], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'getAllApplications' : ActorMethod<[], Array<JobApplication>>,
  'getAllJobs' : ActorMethod<[], Array<JobPosting>>,
  'getAllStudents' : ActorMethod<[], Array<StudentProfile>>,
  'getApplicationsForJob' : ActorMethod<[bigint], Array<JobApplication>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAppRole' : ActorMethod<[], [] | [AppRole]>,
  'getMyApplications' : ActorMethod<[], Array<JobApplication>>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [StudentProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postJob' : ActorMethod<[JobPosting], bigint>,
  'saveCallerUserProfile' : ActorMethod<[StudentProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    undefined
  >,
  'updateJob' : ActorMethod<[bigint, JobPosting], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];